cms/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<slug:slug>/', views.page_view, name='page_view'),
]

home/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from .views import *

from . import views


app_name = 'home' 
urlpatterns = [
    path('', homepage, name='homepage'),  
    path('<int:year>/', views.home_for_year, name='home_for_year'),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),  
]

pyconafrica/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls import handler404, handler500  
from django_robohash.views import robohash 
from django.views.static import serve  
from django.views.generic import RedirectView 


from pyconafrica2019 import views

urlpatterns = [

#Apps
    path('', include('home.urls', namespace='homepage')), 
    path('2019/', include('pyconafrica2019.urls', namespace='pyconafrica2019')),
    path('2020/', include('pycon2020.urls')),
    path('<int:year>/', include([
        path('', include('home.urls')),
        path('about/', include('about.urls')),
        path('speakers/', include('speakers.urls')),
        path('schedule/', include('conference_schedule.urls')),
        path('our-sponsors/', include('sponsors.urls', namespace='sponsors')),
        path('talks/', include('talks.urls', namespace='talks')),
        path('coc/', include('coc.urls')),
        path('sponsor-us/', include('sponsor_us.urls', namespace='sponsor_us')),
        # Add more apps here following the same pattern
        path('h&g/', include('health_safety_guideline.urls', namespace='health_safety_guideline')),
        path('fin-aid/', include('fin_aid.urls', namespace='fin_aid')),
        path('privacy-policy/', include('privacypolicy.urls', namespace='privacypolicy')),
        path('tickets/', include('tickets.urls', namespace='ticket')),

        
        #Leave this last to catch all pages
        path('', include('cms.urls')),   
    ])),
    path('organizers/', admin.site.urls),  

#Thrid party Apps 
    path('summernote/', include('django_summernote.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/profile/', include('registration.urls', namespace='profiles')),  
    path('accounts/', include('registration.backends.default.urls')),
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('robohash/<string>/', robohash, name='robohash'),
    path('avatar/', include('avatar.urls')),
    path('markdownx/', include('markdownx.urls')),
    re_path(r'hitcount/', include('hitcount.urls', namespace='hitcount')),


] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.

handler404 = 'home.views.handler404'




# Modifies default django admin titles and headers with custom app detail.
admin.site.site_header = "PyCon Africa Admin"
admin.site.site_title = "PyCon Africa Admin Portal"
admin.site.index_title = "Welcome to PyCon Africa Portal"

registration/urls.py
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

from .views import *
from . import views
from speakers.views import SpeakerDetailView

app_name = 'registration'

urlpatterns = [  
    path('create_profile/', login_required(CreateProfileView.as_view()), name='create_profile'),
    path('update/<str:pk>/', UpdateProfileView.as_view(), name='profile_update'),  
    path('', login_required(ProfileView.as_view()), name='profile_home'),
    re_path('password_change/(?P<pk>\d+)/', login_required(PasswordView.as_view()), name='password_change'),
    re_path('login_details/(?P<pk>\d+)/', login_required(UpdateLoginView.as_view()), name='login_details'),
    path('profile_updated/', login_required(SuccessView.as_view()), name='profile_update'), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

talks/urls.py
from rest_framework import routers
from django.urls import include, path, re_path
from django.urls import path
from talks.views import TalkViewsSets 
from django.contrib.auth.decorators import login_required
from talks import views
from .views import *  
from django.conf.urls.static import static 
from django.conf import settings 
from django.views.generic import TemplateView

app_name = 'talks'
router = routers.DefaultRouter()
router.register(r'talks', TalkViewsSets)

urlpatterns = [
    # For listing all accepted talks (not year-specific)
    path('accepted_talks/', login_required(views.AcceptedTalksView.as_view()), name='accepted_talks'),
    
    # Submission for a specific year
    path('submit_talk/', login_required(views.submit_talk), name='submit_talk'), 

    # Editing a talk, assuming pk is sufficient for identifying the talk  
    path('<str:pk>/edit_talk/', login_required(views.edit_talk), name='edit_talk'),
    # For listing talks submitted by the logged-in user (not year-specific)
    path('talk_list/', login_required(views.TalkList.as_view()), name='talk_list'), 
    

    # Detail views for talks<int:year>/talks/<int:pk>/talk_details/
    path('<str:pk>/talk_details/', login_required(views.TalkDetailView.as_view()), name='talk_details'), 
    re_path(r'^(?P<pk>[\w-]+)/detail/$', (views.TalksDetailView.as_view()), name='talk_detail'),

    path('<int:year>/talks/success/', SuccessView.as_view(), name='talks_success'),

    # Updated paths to include the year
    path('<int:year>/speaking/', views.speaking, name='speaking'),
    path('<int:year>/proposing_a_talk/', views.proposing, name='proposing'),
    path('<int:year>/recording/', views.recording, name='recording'),
    
    # Redirects for accessing without specifying a year
    path('speaking/', views.speaking, name='speaking_current_year'),
    path('recording/', views.recording, name='recording_current_year'),
    path('proposing_a_talk/', views.proposing, name='proposing_current_year'), 
    path('proposal/<str:pk>/respond/', respond_to_invitation, name='respond_to_invitation'),


    path('submitted', login_required(views.SuccessView.as_view()), name='submitted'),
    path('uploads', views.home, name='home'), 
    path('uploads_simple', views.simple_upload, name='simple_upload'),
    path('uploads_form', views.model_form_upload, name='model_form_upload'),

    #Added Speaker(s) invitation  
    path('<str:pk>/invite-speaker/', views.send_speaker_invitation, name='send_speaker_invitation'),
    path('<str:pk>/accept/', views.accept_invitation, name='accept_invitation'),
    path('<str:pk>/reject/', views.reject_invitation, name='reject_invitation'),

    #Proposal Review 
    path('reviews/', views.list_talks_to_review, name='talks_to_review'), 
    path('review/<str:pk>/', views.review_talk, name='review_talk'),  
    path('review_talk/success/', views.review_success, name='review_success'),
    path('reviewed-by-category/', reviewed_talks_by_category, name='reviewed_talks_by_category'),
    path('reviewed_by_type/', views.reviewed_talks_by_type, name='reviewed_talks_by_type'),
   
    

    ]

urlpatterns += router.urls
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from django_extensions.db.fields import AutoSlugField
from django_slugify_processor.text import slugify
from django.contrib.contenttypes.fields import GenericRelation 
 
from six import python_2_unicode_compatible
from tinymce.models import HTMLField

from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit
@python_2_unicode_compatible
 

class PyConEvent(models.Model):
    name = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    flag_image = models.ImageField(upload_to='countryflags/',default="flag.jpg")
    city = models.CharField(max_length=255, blank=True)
    start_date = models.DateField()
    end_date = models.DateField()
    year = models.IntegerField()  # Year of the Conference
    website_url = models.URLField(blank=True)

    def __str__(self):
        return f"{self.name} {self.year}"

    class Meta:
        ordering = ['start_date']


class EventYear(models.Model):
    year = models.IntegerField(unique=True)
    home_info = models.TextField(blank=True, null=True)
    template_path = models.CharField(max_length=255, default="home/home.html", help_text="Path to the year's templates, e.g., '2020/home/home.html'")

    def __str__(self):
        return f"PyCon Africa {self.year}"

    class Meta:
        verbose_name = 'Event Year'
        verbose_name_plural = 'Event Years'

home/forms.py
from django import forms
from .models import *

home/views.py
from django.shortcuts import render,  get_object_or_404, redirect
from django.utils import timezone
from django.views.generic import ListView
from django.template import RequestContext
from django.views.generic.detail import DetailView
from .forms import *
from hitcount.views import HitCountDetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from next_prev import next_in_order, prev_in_order 
from django.utils.timezone import now
from .models import *  
from .models import EventYear
from fin_aid.models import Fin_aid

def get_fin_aid_status(year):
    event_year = get_object_or_404(EventYear, year=year)
    fin_aids = Fin_aid.objects.filter(event_year=event_year).order_by('-date_created')
    fin_aid_status = []

    for fin_aid in fin_aids:
        status = {
            'is_open': fin_aid.is_form_open(),
            'is_closed': fin_aid.is_form_closed(),
            'not_open_yet': fin_aid.is_form_not_open_yet(),
            'form_status_message': fin_aid.get_form_status_message()
        }
        fin_aid_status.append(status)

    return fin_aid_status

def homepage(request):
    current_year = now().year
    upcoming_pycon_events = PyConEvent.objects.filter(start_date__gte=now()).exclude(year=current_year)
    pycon_africa_this_year = EventYear.objects.filter(year=current_year).first()
    fin_aid_status = get_fin_aid_status(current_year)
    
    context = {
        'upcoming_pycon_events': upcoming_pycon_events,
        'pycon_africa_this_year': pycon_africa_this_year,
        'current_year': current_year,
        'fin_aid_status': fin_aid_status,
    }
    
    return render(request, 'home/home.html', context)


def home_for_year(request, year):
    event_year = EventYear.objects.get(year=year)
    template_name = f"{event_year.template_path}"
    context = {
        # Your context data here
        'event_year': event_year,
    }
    return render(request, template_name, context)

 
 


def handler404(request, exception):
    return render(request, '404.html', locals())

 

templates/profiles/create_profile.html
{% extends "base.html" %}
{% load i18n static avatar_tags crispy_forms_tags %}
{% block meta_title %}{% if page %}{{ page.meta_title }}{% else %}{% trans "Create Profile || PyCon Africa" %}{% endif %}{% endblock %}


{% block content %}

<!-- ========== HEADER ========== -->
{% include '2024/navbar.html' %}
<!-- ========== END HEADER ========== -->
 

    <!-- Breadcrumbs -->
    <section class="g-bg-gray-light-v5 g-py-80 g-pt-150">
      <div class="container text-center">
        <h2 class="h2 g-color-black g-font-weight-600">Create your Profile {% if user_profile.surname %}{{ request.user.user_profile.name }} {% else %}{% firstof user.get_short_name user.get_username|capfirst %}{% endif %}</h2>

        <ul class="u-list-inline">
          <li class="list-inline-item g-mr-5">
            <a class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover" href="#">Home</a>
            <i class="g-color-gray-light-v2 g-ml-5">/</i>
          </li> 
          <li class="list-inline-item g-color-primary">
            <span>Create Profile</span>
          </li>
        </ul><br> 
        <i class="fa-solid fa-user-plus" style="font-size:41px;"></i>
      </div>
      
    </section>
    <!-- End Breadcrumbs --> 
   
  
      <section class="g-mb-100">
        <div class="container">
          <div class="row">
            <!-- Profile Sidebar -->
            <div class="col-lg-3 g-mb-50 g-mb-0--lg"> 
              <!-- Profile Pic --> 
                {% include 'profiles/profilepic_side.html' %}
              <!-- End Profile Pic  -->   
  
              <!-- Sidebar Navigation -->
              <div class="list-group list-group-border-0 g-mb-40">
                <div class="media"> 
                  <div class="media-body">
                    <div><b><small class="text-danger">LAST LOGIN</small></b></div>
                    <div class="g-font-size-12 g-color-gray-dark-v2"><b><small>Date:</small></b>  {{ request.user.last_login.date }}</div>
                    <div class="g-font-size-12  g-color-gray-dark-v2"><b><small>Time:</small></b>  {{ request.user.last_login.time }}</div> 
                  </div>
                </div>
              </div> 
                
              
              {% if user_profile %}   
              
                <!-- Overall -->
                <a href="{% url 'profiles:profile_update' pk=request.user.user_profile.profile_id.hashid  %}" class="list-group-item justify-content-between active">
                  <span><i class="icon-home g-pos-rel g-top-1 g-mr-8"></i> Overall</span>
                  <span class="u-label g-font-size-11 g-bg-white g-color-main g-rounded-20 g-px-10">2</span>
                </a>
                <!-- End Overall -->
                
                <!-- Overall -->
                <a href="{% url 'profiles:profile_update' pk=request.user.user_profile.profile_id.hashid  %}" class="list-group-item justify-content-between active">
                  <span><i class="fa-light fa-id-card g-pos-rel g-top-1 g-mr-8"></i>  Update my Profile</span> 
                </a>
                <!-- End Overall -->
  
                <!-- Profile -->
                <a href="/accounts/password/change/" class="list-group-item list-group-item-action justify-content-between">
                  <span><i class="fa-light fa-lock g-pos-rel g-top-1 g-mr-8"></i>  Change Password</span>
                </a>
                <!-- End Profile -->
   
                <!-- Profile -->
                <a href="{% url 'talks:talk_list' year=year %}" class="list-group-item list-group-item-action justify-content-between">
                  <span><i class="fa-light fa-podium-star g-pos-rel g-top-1 g-mr-8"></i>  My Submitted Talks</span>
                </a>
                <!-- End Profile -->
    
              
                <br> 
                <p><a href=""class="btn warn"><i class="fa-light fa-id-card" style="font-size:21px;"></i>&nbsp;&nbsp; Update my Profile</a></p>
                <p><a href="/accounts/password/change/"class="btn warn"><i class="fa-light fa-lock" style="font-size:21px;"></i>&nbsp;&nbsp; Change Password</a></p>
                <p><a href="{% url 'talks:talk_list' year=year %}"class="btn warn"><i class="fa-light fa-podium-star" style="font-size:21px;"></i>&nbsp;&nbsp; My Submitted Talks</a></p>
                       
                
              {% else %}
              
              {% endif %}<br>
  
              </div>
              <!-- End Sidebar Navigation -->  
            <!-- End Profile Sidebar -->  
   
              <div class="col-lg-9">
                <section class="g-brd-around g-brd-gray-light-v4">
                  <div class="container g-py-50--md g-py-20">
                    
                    <div class="panel wow fadeInLeft col-md-7">  
                        <p class="mad-sub-title">Enter your profile details below</p>
                        <form action="{% url 'profiles:create_profile' %}" enctype='multipart/form-data' method='Post'>{% csrf_token %}
                        
                            {{ form|crispy }} 
                            {{ form.media }}
                            <br> 
                            <div class="d-grid gap-5">  
                                
                                <button class="btn btn-md u-btn-primary rounded-0" id="submit-id-update"  style="background-position: 0px 59px;" type="submit" >Create Profile<i class="licon-chevron-right-circle"></i></button>
                                 
                            </div> 
                         </form>
                    </div>


                </div>
                </section> 
              </div>    
   
          </div>
        </div>
      </section> 
    <!-- end section.speakers -->
 
    
{% endblock %}

 

templates/profiles/login_details.html
{% extends "base2.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md-3">

    </div>
    <div class="col-md-6">
<h2>Update your login details</h2>
<br>

<form action="" method=post>
    {% crispy form form.helper %}
          {% csrf_token %}
</form>

      </div>
    <div class="col-md-3">

    </div>
</div>

{% endblock %}

templates/profiles/password_change.html
{% extends "base2.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md-3">

    </div>
    <div class="col-md-6">
<h2>Change your password</h2>
<br>

<form action="{% url 'profiles:password_change' user.pk %}" method=post>
    {% crispy form form.helper %}
          {% csrf_token %}
</form>

      </div>
    <div class="col-md-3">

    </div>
</div>

{% endblock %}

templates/profiles/profilepic_nav.html
{% load  avatar_tags static profile_tags %} 

<div class="mad-shedule-person">
    <div class="mad-person-img">


      {% if request.user.profile.is_visible == True %}          
    <a class="mad-team-member-photo mad--ln-independent "><img  class="img-circle img-responsive"  src="{{ request.user.profile.profile_image.url}}" width=40 height=40 alt=""></a> 
      {% else %} 
      <img class="img-circle img-responsive" src="/robohash/{% firstof user.get_short_name user.get_username|capfirst %}/?width=40&height=40" alt="">
      {% endif %}
    </div>
    </div>

templates/profiles/profilepic_side.html
{% load  avatar_tags static profile_tags %} 

 <!-- User Image -->
 <div class="u-block-hover g-pos-rel">
    {% if request.user.user_profile.profile_image %} 
    <figure>
      <img class="img-fluid w-100 u-block-hover__main--zoom-v1" src="{{ request.user.user_profile.profile_image.url }}" alt="Image Description">
    </figure>
    {% else %}  
    <figure>
      <img class="img-fluid w-100 u-block-hover__main--zoom-v1" src="/robohash/{% firstof user.get_short_name user.get_username|capfirst %}/?width=110&height=110" alt="Image Description">
    </figure>

    {% endif %}   
  </div>
  <!-- User Image -->
 

templates/profiles/success.html
{% extends "base2.html" %}

{% block content %}
<div class="row">
    <div class="col-md-2">

    </div>
	    <div class="col-md-8">
				<h2> Profile Update Successful! </h2>
				<br>
				<p>Your changes have been updated successfully.
				</p>

	   </div>
    <div class="col-md-2">

    </div>
</div>

{% endblock %}

templates/profiles/update.html
{% extends "base.html" %}
{% load i18n static avatar_tags crispy_forms_tags countries profile_tags %}
{% block meta_title %}{% if page %}{{ page.meta_title }}{% else %}{% trans "Update Profile || PyCon Africa" %}{% endif %}{% endblock %}


{% block content %}

<!-- ========== HEADER ========== -->
{% include '2024/navbar.html' %}
<!-- ========== END HEADER ========== -->
 

    <!-- Breadcrumbs -->
    <section class="g-bg-gray-light-v5 g-py-80 g-pt-150">
      <div class="container text-center">
        <h2 class="h2 g-color-black g-font-weight-600">About Us</h2>

        <ul class="u-list-inline">
          <li class="list-inline-item g-mr-5">
            <a class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover" href="2024">Home</a>
            <i class="g-color-gray-light-v2 g-ml-5">/</i>
          </li> 
          <li class="list-inline-item g-mr-5">
            <a class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover" href="/accounts/profile/">Profile</a>
            <i class="g-color-gray-light-v2 g-ml-5">/</i>
          </li> 
          <li class="list-inline-item g-color-primary">
            <span>Update</span>
          </li>
        </ul><br> 
        <i class="fa-solid fa-user-pen" style="font-size:41px;"></i>
      </div>
      
    </section>
    <!-- End Breadcrumbs --> 
    
  
      <section class="g-mb-100 g-pt-50">
        <div class="container">
          <div class="u-shadow-v1-5 g-line-height-2 g-pa-40 g-mb-30" >  
              <div class="row">
              
                <!-- Profile Sidebar -->
                <div class="col-lg-3 g-mb-50 g-mb-0--lg"> 
                  <!-- Profile Pic --> 
                    {% include 'profiles/profilepic_side.html' %}
                  <!-- End Profile Pic  -->   
      
                  <!-- Sidebar Navigation -->
                  <div class="list-group list-group-border-0 g-mb-40">
                    <div class="media"> 
                      <div class="media-body">
                        <div><b><small class="text-danger">LAST LOGIN</small></b></div>
                        <div class="g-font-size-12 g-color-gray-dark-v2"><b><small>Date:</small></b>  {{ request.user.last_login.date }}</div>
                        <div class="g-font-size-12  g-color-gray-dark-v2"><b><small>Time:</small></b>  {{ request.user.last_login.time }}</div> 
                      </div>
                    </div>
                  </div> 
                    
                    <!-- Overall -->
                    <a href="/accounts/profile/" class="list-group-item list-group-item-action justify-content-between">
                      <span><i class="icon-home g-pos-rel g-top-1 g-mr-8"></i> My Profile</span> 
                    </a>
                    <!-- End Overall -->
                    
                    <!-- Overall -->
                    <a href="{% url 'profiles:profile_update' pk=request.user.user_profile.profile_id.hashid  %}" class="list-group-item list-group-item-action justify-content-between active">
                      <span><i class="fa-solid fa-fade fa-id-card g-pos-rel g-top-1 g-mr-8"></i>  Update my Profile</span> 
                    </a>
                    <!-- End Overall -->
      
                    <!-- Profile -->
                    <a href="/accounts/password/change/" class="list-group-item list-group-item-action justify-content-between">
                      <span><i class="fa-light fa-lock g-pos-rel g-top-1 g-mr-8"></i>  Change Password</span>
                    </a>
                    <!-- End Profile -->
      
                    <!-- Profile -->
                    <a href="{% url 'talks:talk_list' year=year %}" class="list-group-item list-group-item-action justify-content-between">
                      <span><i class="fa-light fa-podium-star g-pos-rel g-top-1 g-mr-8"></i>  My Submitted Talks</span>
                    </a>
                    <!-- End Profile -->

                    <!-- My Submitted Talks -->
                    <a href="{% url 'talks:submit_talk' year=year %}" class="list-group-item list-group-item-action justify-content-between">
                        <span><i class="fa-light fa-podium g-pos-rel g-top-1 g-mr-8"></i>  Submit a new Talk</span>
                      </a>
                      <!-- End Profile -->
        
                      {% if perms.reviews.add_review %} 
                      <!-- Review Talks -->
                      <a href="{% url 'talks:talks_to_review' year=2024 %}" class="list-group-item list-group-item-action justify-content-between ">
                        <span><i class="fa-thin fa-ballot-check g-pos-rel g-top-1 g-mr-8"></i> Review Proposals</span>
                      </a>
                      <!-- End Profile --> 
                    {% endif %}

                    
                    
                    {% if request.user.is_superuser %}
                   <!-- Review Talks List-->
                   <a href="{% url 'talks:reviewed_talks_by_category' year=2024 %}" class="list-group-item list-group-item-action justify-content-between ">
                    <span><i class="fa-thin fa-list-check g-pos-rel g-top-1 g-mr-8"></i> Proposals by Category</span>
                  </a>
                  <!-- End Profile --> 
                        {% endif %}
    
      
                  </div>
                  <!-- End Sidebar Navigation -->  
                <!-- End Profile Sidebar -->  
    
      
                  <div class="col-lg-9">
                    <section class="g-brd-around g-brd-gray-light-v4">
                      <div class="container g-py-50--md g-py-20">
                        
                        <div class="panel wow fadeInLeft ">  
                          <h4 class="mad-sub-title">Update your details below</h4><br> 
                            <form action="{% url 'profiles:create_profile' %}" enctype='multipart/form-data' method='Post'>{% csrf_token %}
                            
                                {{ form|crispy }} 
                                {{ form.media }}
                                <br> 
                                <div class="d-grid gap-5">  
                                    
                                    <button class="btn btn-md u-btn-primary rounded-0" id="submit-id-update"  style="background-position: 0px 59px;" type="submit" >Update Profile<i class="licon-chevron-right-circle"></i></button>
                                    
                                </div> 
                            </form>
                        </div>


                    </div>
                    </section> 
                  </div>    
      
              </div>
          </div>
        </div>
      </section> 
    <!-- end section.speakers -->
 
 


{% endblock %}

 